kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-share
  namespace: kube-public
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10G
  storageClassName: glusterfs
