---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyterhub-ingress-ui
  namespace: kube-public
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: jupyterhub.com.cn
    http:
      paths:
        - path: /
          backend:
            serviceName: proxy-public
            servicePort: 80
