{{- if and .Values.proxy.https.enabled .Values.proxy.https.hosts }}
# This is solely used to provide auto HTTPS with our bundled kube-lego
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyterhub-internal
  annotations:
    kubernetes.io/ingress.provider: nginx
    kubernetes.io/ingress.class: jupyterhub-proxy-tls
    hub.jupyter.org/tls-terminator: "true"
spec:
  rules:
    {{- range $host := .Values.proxy.https.hosts }}
    - http:
        paths:
          - path: /
            backend:
              serviceName: proxy-http
              servicePort: 8000
      host: {{ $host }}
    {{- end }}
  tls:
    {{- if eq .Values.proxy.https.type "letsencrypt" }}
    - secretName: kubelego-tls-proxy-{{ .Release.Name }}
    {{- else if eq .Values.proxy.https.type "manual" }}
    - secretName: manual-tls-proxy-{{ .Release.Name }}
    {{- else }}
    # unhandled type
    # it would be nice if helm had an `error` function
    {{ required (printf "https.type must be 'manual' or 'letsencrypt', not '%s'" .Values.proxy.https.type)  ._undefined }}
    {{- end }}
      hosts:
{{ toYaml .Values.proxy.https.hosts | indent 8 }}
{{- end }}
