apiVersion: v1
kind: Service
metadata:
  name: proxy-api
spec:
  selector:
    name: proxy
    component: proxy
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-http
  # toYaml + indent seem a lot more unstable & error prone
  annotations: {{ toJson .Values.proxy.service.annotations }}
  labels: {{ toJson .Values.proxy.service.labels }}
spec:
  type: ClusterIP
  selector:
    name: proxy
    component: proxy
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: proxy
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{ if .Values.proxy.service.labels -}}
{{ toYaml .Values.proxy.service.labels | indent 4 }}
  {{- end }}
  {{ if .Values.proxy.service.annotations -}}
  annotations:
{{ toYaml .Values.proxy.service.annotations | indent 4 }}
  {{- end }}
  name: proxy-public
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      # allow proxy.service.nodePort for http
      {{ if .Values.proxy.service.nodePorts.http -}}
      nodePort: {{ .Values.proxy.service.nodePorts.http }}
      {{- end }}
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
      {{ if .Values.proxy.service.nodePorts.https -}}
      nodePort: {{ .Values.proxy.service.nodePorts.https }}
      {{- end }}
  selector:
    name: proxy
    component: proxy
    release: {{ .Release.Name }}
  type: {{ .Values.proxy.service.type }}
  {{ if .Values.proxy.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.proxy.service.loadBalancerIP }}
  {{- end }}
